# Generated by Django 4.2.7 on 2025-09-05 12:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Frais de livraison (FCFA)')),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=25000, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Seuil livraison gratuite (FCFA)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Paramètre de livraison',
                'verbose_name_plural': 'Paramètres de livraison',
            },
        ),
    ]
