# Generated by Django 4.2.7 on 2025-09-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitemcustomization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paydunya', 'PayDunya'), ('wave_direct', 'Wave Direct'), ('cash_on_delivery', 'Paiement à la livraison')], default='paydunya', max_length=50, verbose_name='Méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payé'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cash_on_delivery', 'Paiement à la livraison')], default='pending', max_length=20, verbose_name='Statut du paiement'),
        ),
    ]
