# Generated by Django 4.2.7 on 2025-09-05 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_orderitemcustomization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0004_remove_wave_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='Serveur SMTP')),
                ('smtp_port', models.IntegerField(default=587, verbose_name='Port SMTP')),
                ('smtp_username', models.EmailField(max_length=254, verbose_name='Email SMTP')),
                ('smtp_password', models.CharField(max_length=100, verbose_name='Mot de passe SMTP')),
                ('use_tls', models.BooleanField(default=True, verbose_name='Utiliser TLS')),
                ('from_email', models.EmailField(max_length=254, verbose_name='Email expéditeur')),
                ('from_name', models.CharField(default='Maillots Football', max_length=100, verbose_name='Nom expéditeur')),
                ('is_active', models.BooleanField(default=True, verbose_name='Système actif')),
                ('send_order_confirmations', models.BooleanField(default=True, verbose_name='Confirmer les commandes')),
                ('send_payment_confirmations', models.BooleanField(default=True, verbose_name='Confirmer les paiements')),
                ('send_shipping_notifications', models.BooleanField(default=True, verbose_name="Notifications d'expédition")),
                ('send_cart_reminders', models.BooleanField(default=True, verbose_name='Rappels de panier')),
                ('send_stock_alerts', models.BooleanField(default=True, verbose_name='Alertes de stock')),
                ('max_emails_per_hour', models.IntegerField(default=100, verbose_name='Max emails/heure')),
                ('cart_reminder_delay_hours', models.IntegerField(default=24, verbose_name='Délai rappel panier (heures)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Configuration Email',
                'verbose_name_plural': 'Configurations Email',
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du template')),
                ('template_type', models.CharField(choices=[('order_confirmation', 'Confirmation de commande'), ('payment_confirmation', 'Confirmation de paiement'), ('order_shipped', 'Commande expédiée'), ('order_delivered', 'Commande livrée'), ('cart_reminder', 'Rappel de panier abandonné'), ('stock_alert', 'Alerte stock faible'), ('promotion', 'Email de promotion'), ('welcome', 'Email de bienvenue')], max_length=50, verbose_name='Type de template')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('html_content', models.TextField(verbose_name='Contenu HTML')),
                ('text_content', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Template Email',
                'verbose_name_plural': 'Templates Email',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email destinataire')),
                ('recipient_name', models.CharField(blank=True, max_length=100, verbose_name='Nom destinataire')),
                ('subject', models.CharField(max_length=200, verbose_name='Sujet')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('sent', 'Envoyé'), ('failed', 'Échoué'), ('bounced', 'Retourné')], default='pending', max_length=20, verbose_name='Statut')),
                ('email_data', models.JSONField(default=dict, verbose_name='Données email')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Envoyé le')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order', verbose_name='Commande')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment', verbose_name='Paiement')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.emailtemplate', verbose_name='Template')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Log Email',
                'verbose_name_plural': 'Logs Email',
                'ordering': ['-created_at'],
            },
        ),
    ]
